defaults:
  - _self_
  - model: base
  - optimizer: adamw
  - train: base
  - data: fl_iid
  - algorithm: fed_avg
float: True
name: cnn_base
save_npz: False
hydra:
  run:
    dir: ./runs/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
